name: Create tag and release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-openapi-generator:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Создать и пушнуть тег
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
